version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "80:80"
    expose:
      - "80"
    stdin_open: true
    tty: true
    volumes:
      - ./:/opt/app
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
    command: nginx
    networks:
      - dev-network

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./:/opt/app
    stdin_open: true
    tty: true
    command: php-fpm
    networks:
      - dev-network

  db:
    image: percona
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - dev-network

  redis:
    image: redis
    ports:
      - 6379
    networks:
      - dev-network

  redis-session:
    image: redis
    ports:
      - 6379
    networks:
      - dev-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  dbdata:
    driver: local