version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    expose:
      - 80
    stdin_open: true
    tty: true
    volumes:
      - ./public:/opt/app
      - ~/.composer:/var/www/.composer
      - ~/.npm:/var/www/.npm
    environment:
      XDEBUG_CONFIG: "remote_host=localhost"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db
    links:
      - db
      - php-fpm
    command: nginx
    networks:
      - dev-network

  php-fpm:
    build:
      context: .
      dockerfile: .docker/php-fpm/Dockerfile
    container_name: php-fpm
    ports:
      - 9000:9000
    expose:
      - 9000
    volumes:
      - ./public:/opt/app
    stdin_open: true
    tty: true
    command: php-fpm
    networks:
      - dev-network

  db:
    image: percona
    container_name: db
    ports:
      - 3300:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - dev-network
    links:
      - db

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379
    networks:
      - dev-network

  redis-session:
    image: redis
    container_name: redis-session
    ports:
      - 6379
    networks:
      - dev-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  dbdata:
    driver: local